services:
    app:
        build:
            args:
                user: usuario
                uid: 1000
            context: ./
            dockerfile: docker/Dockerfile
        image: araujoleonardo/laravel-app
        container_name: laravel-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
        restart: always
        networks:
            - laravel-app

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
            - "80:80" #http
            - "443:443" #https
        volumes:
            - ./:/var/www/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-app

    pgsql:
        image: postgres:16-bullseye
        container_name: pgsql
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/postgresql:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel-app

#    pgadmin:
#        depends_on:
#            - pgsql
#        image: dpage/pgadmin4
#        container_name: pgadmin
#        restart: always
#        ports:
#            - "8080:80"
#        environment:
#            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#        networks:
#            - laravel-app

networks:
    laravel-app:
        driver: bridge
